import 'package:flutter/material.dart';

Map<String, IconData> itemIcons = {
  'Sofa': Icons.chair,
  'Table': Icons.table_chart,
  'Chair': Icons.event_seat,
  'Cot': Icons.bed,
  'Mattress': Icons.bedroom_baby,
  'Cupboard': Icons.inventory,
  'Misc.': Icons.miscellaneous_services,
  'TV': Icons.tv,
  'Refrigerator': Icons.kitchen,
  'Washing Machine': Icons.local_laundry_service,
  'Oven': Icons.microwave,
  'Air conditioner': Icons.ac_unit,
  'Fans/Coolers': Icons.toys,
  'Cycle': Icons.pedal_bike,
  'Bike': Icons.motorcycle,
  'Car': Icons.directions_car,
  'Gym / Sports': Icons.fitness_center,
  'Musical Instruments': Icons.music_note,
  'Fragile': Icons.warning_amber_rounded,
  'Home Appliances': Icons.home_repair_service,
  'Utility': Icons.build,
  'Boxes/Trolley': Icons.local_shipping,
};
